//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.17 at 07:34:43 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://rs.tdwg.org/UBIF/2006/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package sdd;
