//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.09 at 10:08:12 AM MST 
//


package annotationSchema.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}genus_name"/>
 *         &lt;element ref="{}genus_authority" minOccurs="0"/>
 *         &lt;element ref="{}species_name" minOccurs="0"/>
 *         &lt;element ref="{}species_authority" minOccurs="0"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{}subspecies_name"/>
 *           &lt;element ref="{}subspecies_authority"/>
 *         &lt;/sequence>
 *         &lt;element ref="{}variety_name" minOccurs="0"/>
 *         &lt;element ref="{}variety_authority" minOccurs="0"/>
 *         &lt;element ref="{}place_of_publication" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Status" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "genusName",
    "genusAuthority",
    "speciesName",
    "speciesAuthority",
    "subspeciesName",
    "subspeciesAuthority",
    "varietyName",
    "varietyAuthority",
    "placeOfPublication"
})
@XmlRootElement(name = "TaxonIdentification")
public class TaxonIdentification {

    @XmlElement(name = "genus_name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String genusName;
    @XmlElement(name = "genus_authority")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String genusAuthority;
    @XmlElement(name = "species_name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String speciesName;
    @XmlElement(name = "species_authority")
    protected String speciesAuthority;
    @XmlElement(name = "subspecies_name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String subspeciesName;
    @XmlElement(name = "subspecies_authority")
    protected String subspeciesAuthority;
    @XmlElement(name = "variety_name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String varietyName;
    @XmlElement(name = "variety_authority")
    protected String varietyAuthority;
    @XmlElement(name = "place_of_publication")
    protected List<PlaceOfPublication> placeOfPublication;
    @XmlAttribute(name = "Status", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String status;

    /**
     * Gets the value of the genusName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenusName() {
        return genusName;
    }

    /**
     * Sets the value of the genusName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenusName(String value) {
        this.genusName = value;
    }

    /**
     * Gets the value of the genusAuthority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenusAuthority() {
        return genusAuthority;
    }

    /**
     * Sets the value of the genusAuthority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenusAuthority(String value) {
        this.genusAuthority = value;
    }

    /**
     * Gets the value of the speciesName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpeciesName() {
        return speciesName;
    }

    /**
     * Sets the value of the speciesName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpeciesName(String value) {
        this.speciesName = value;
    }

    /**
     * Gets the value of the speciesAuthority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpeciesAuthority() {
        return speciesAuthority;
    }

    /**
     * Sets the value of the speciesAuthority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpeciesAuthority(String value) {
        this.speciesAuthority = value;
    }

    /**
     * Gets the value of the subspeciesName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubspeciesName() {
        return subspeciesName;
    }

    /**
     * Sets the value of the subspeciesName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubspeciesName(String value) {
        this.subspeciesName = value;
    }

    /**
     * Gets the value of the subspeciesAuthority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubspeciesAuthority() {
        return subspeciesAuthority;
    }

    /**
     * Sets the value of the subspeciesAuthority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubspeciesAuthority(String value) {
        this.subspeciesAuthority = value;
    }

    /**
     * Gets the value of the varietyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVarietyName() {
        return varietyName;
    }

    /**
     * Sets the value of the varietyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVarietyName(String value) {
        this.varietyName = value;
    }

    /**
     * Gets the value of the varietyAuthority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVarietyAuthority() {
        return varietyAuthority;
    }

    /**
     * Sets the value of the varietyAuthority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVarietyAuthority(String value) {
        this.varietyAuthority = value;
    }

    /**
     * Gets the value of the placeOfPublication property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the placeOfPublication property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlaceOfPublication().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PlaceOfPublication }
     * 
     * 
     */
    public List<PlaceOfPublication> getPlaceOfPublication() {
        if (placeOfPublication == null) {
            placeOfPublication = new ArrayList<PlaceOfPublication>();
        }
        return this.placeOfPublication;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

}
