//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.11 at 12:08:08 PM EDT 
//


package annotationSchema.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}number"/>
 *         &lt;choice>
 *           &lt;element ref="{}family_name"/>
 *           &lt;element ref="{}genus_name"/>
 *           &lt;element ref="{}species_name"/>
 *           &lt;element ref="{}subgenus_name"/>
 *           &lt;element ref="{}subspecies_name"/>
 *           &lt;element ref="{}tribe_name"/>
 *           &lt;element ref="{}variety_name"/>
 *         &lt;/choice>
 *         &lt;element ref="{}authority" minOccurs="0"/>
 *         &lt;element ref="{}place_of_publication" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{}conserved"/>
 *           &lt;element ref="{}past_name"/>
 *         &lt;/choice>
 *         &lt;element ref="{}common_name" minOccurs="0"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{}synonym_of_family"/>
 *           &lt;element ref="{}author_of_family" maxOccurs="unbounded"/>
 *         &lt;/sequence>
 *         &lt;element ref="{}derivation" minOccurs="0"/>
 *         &lt;element ref="{}author_of_tribe_genus" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{}synonym_of_genus_name"/>
 *           &lt;element ref="{}synonym_of_species_name"/>
 *           &lt;element ref="{}synonym_of_subspecies_name"/>
 *           &lt;element ref="{}synonym_of_tribe_genus"/>
 *           &lt;element ref="{}synonym_of_tribe_name"/>
 *           &lt;element ref="{}synonym_of_variety_name"/>
 *         &lt;/choice>
 *         &lt;element ref="{}description"/>
 *         &lt;element ref="{}number_of_infrataxa" minOccurs="0"/>
 *         &lt;element ref="{}flowering_time" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}habitat" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}conservation" minOccurs="0"/>
 *         &lt;element ref="{}elevation" minOccurs="0"/>
 *         &lt;element ref="{}introduced" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;choice maxOccurs="unbounded" minOccurs="0">
 *             &lt;element ref="{}ca_distribution"/>
 *             &lt;element ref="{}global_distribution"/>
 *             &lt;element ref="{}us_distribution"/>
 *           &lt;/choice>
 *           &lt;element ref="{}general_distribution" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{}couplet"/>
 *           &lt;element ref="{}discussion"/>
 *           &lt;element ref="{}key"/>
 *           &lt;element ref="{}references"/>
 *           &lt;element ref="{}run_in_sidehead"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "number",
    "familyName",
    "genusName",
    "speciesName",
    "subgenusName",
    "subspeciesName",
    "tribeName",
    "varietyName",
    "authority",
    "placeOfPublication",
    "conserved",
    "pastName",
    "commonName",
    "synonymOfFamily",
    "authorOfFamily",
    "derivation",
    "authorOfTribeGenus",
    "synonymOfGenusName",
    "synonymOfSpeciesName",
    "synonymOfSubspeciesName",
    "synonymOfTribeGenus",
    "synonymOfTribeName",
    "synonymOfVarietyName",
    "description",
    "numberOfInfrataxa",
    "floweringTime",
    "habitat",
    "conservation",
    "elevation",
    "introduced",
    "caDistributionOrGlobalDistributionOrUsDistribution",
    "generalDistribution",
    "coupletOrDiscussionOrKey"
})
@XmlRootElement(name = "treatment")
public class Treatment {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String number;
    @XmlElement(name = "family_name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String familyName;
    @XmlElement(name = "genus_name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String genusName;
    @XmlElement(name = "species_name")
    protected String speciesName;
    @XmlElement(name = "subgenus_name")
    protected String subgenusName;
    @XmlElement(name = "subspecies_name")
    protected String subspeciesName;
    @XmlElement(name = "tribe_name")
    protected String tribeName;
    @XmlElement(name = "variety_name")
    protected String varietyName;
    protected String authority;
    @XmlElement(name = "place_of_publication")
    protected String placeOfPublication;
    protected String conserved;
    @XmlElement(name = "past_name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String pastName;
    @XmlElement(name = "common_name")
    protected String commonName;
    @XmlElement(name = "synonym_of_family")
    protected String synonymOfFamily;
    @XmlElement(name = "author_of_family")
    protected List<String> authorOfFamily;
    protected String derivation;
    @XmlElement(name = "author_of_tribe_genus")
    protected List<String> authorOfTribeGenus;
    @XmlElement(name = "synonym_of_genus_name")
    protected String synonymOfGenusName;
    @XmlElement(name = "synonym_of_species_name")
    protected String synonymOfSpeciesName;
    @XmlElement(name = "synonym_of_subspecies_name")
    protected String synonymOfSubspeciesName;
    @XmlElement(name = "synonym_of_tribe_genus")
    protected String synonymOfTribeGenus;
    @XmlElement(name = "synonym_of_tribe_name")
    protected String synonymOfTribeName;
    @XmlElement(name = "synonym_of_variety_name")
    protected String synonymOfVarietyName;
    @XmlElement(required = true)
    protected Description description;
    @XmlElement(name = "number_of_infrataxa")
    protected String numberOfInfrataxa;
    @XmlElement(name = "flowering_time")
    protected List<String> floweringTime;
    protected List<String> habitat;
    protected String conservation;
    protected String elevation;
    protected String introduced;
    @XmlElementRefs({
        @XmlElementRef(name = "global_distribution", type = JAXBElement.class),
        @XmlElementRef(name = "ca_distribution", type = JAXBElement.class),
        @XmlElementRef(name = "us_distribution", type = JAXBElement.class)
    })
    protected List<JAXBElement<String>> caDistributionOrGlobalDistributionOrUsDistribution;
    @XmlElement(name = "general_distribution")
    protected List<String> generalDistribution;
    @XmlElementRefs({
        @XmlElementRef(name = "key", type = JAXBElement.class),
        @XmlElementRef(name = "references", type = JAXBElement.class),
        @XmlElementRef(name = "run_in_sidehead", type = JAXBElement.class),
        @XmlElementRef(name = "couplet", type = JAXBElement.class),
        @XmlElementRef(name = "discussion", type = JAXBElement.class)
    })
    protected List<JAXBElement<String>> coupletOrDiscussionOrKey;

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumber(String value) {
        this.number = value;
    }

    /**
     * Gets the value of the familyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFamilyName() {
        return familyName;
    }

    /**
     * Sets the value of the familyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFamilyName(String value) {
        this.familyName = value;
    }

    /**
     * Gets the value of the genusName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenusName() {
        return genusName;
    }

    /**
     * Sets the value of the genusName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenusName(String value) {
        this.genusName = value;
    }

    /**
     * Gets the value of the speciesName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpeciesName() {
        return speciesName;
    }

    /**
     * Sets the value of the speciesName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpeciesName(String value) {
        this.speciesName = value;
    }

    /**
     * Gets the value of the subgenusName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubgenusName() {
        return subgenusName;
    }

    /**
     * Sets the value of the subgenusName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubgenusName(String value) {
        this.subgenusName = value;
    }

    /**
     * Gets the value of the subspeciesName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubspeciesName() {
        return subspeciesName;
    }

    /**
     * Sets the value of the subspeciesName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubspeciesName(String value) {
        this.subspeciesName = value;
    }

    /**
     * Gets the value of the tribeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTribeName() {
        return tribeName;
    }

    /**
     * Sets the value of the tribeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTribeName(String value) {
        this.tribeName = value;
    }

    /**
     * Gets the value of the varietyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVarietyName() {
        return varietyName;
    }

    /**
     * Sets the value of the varietyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVarietyName(String value) {
        this.varietyName = value;
    }

    /**
     * Gets the value of the authority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthority() {
        return authority;
    }

    /**
     * Sets the value of the authority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthority(String value) {
        this.authority = value;
    }

    /**
     * Gets the value of the placeOfPublication property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlaceOfPublication() {
        return placeOfPublication;
    }

    /**
     * Sets the value of the placeOfPublication property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlaceOfPublication(String value) {
        this.placeOfPublication = value;
    }

    /**
     * Gets the value of the conserved property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConserved() {
        return conserved;
    }

    /**
     * Sets the value of the conserved property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConserved(String value) {
        this.conserved = value;
    }

    /**
     * Gets the value of the pastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPastName() {
        return pastName;
    }

    /**
     * Sets the value of the pastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPastName(String value) {
        this.pastName = value;
    }

    /**
     * Gets the value of the commonName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommonName() {
        return commonName;
    }

    /**
     * Sets the value of the commonName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommonName(String value) {
        this.commonName = value;
    }

    /**
     * Gets the value of the synonymOfFamily property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSynonymOfFamily() {
        return synonymOfFamily;
    }

    /**
     * Sets the value of the synonymOfFamily property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSynonymOfFamily(String value) {
        this.synonymOfFamily = value;
    }

    /**
     * Gets the value of the authorOfFamily property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the authorOfFamily property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAuthorOfFamily().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAuthorOfFamily() {
        if (authorOfFamily == null) {
            authorOfFamily = new ArrayList<String>();
        }
        return this.authorOfFamily;
    }

    /**
     * Gets the value of the derivation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDerivation() {
        return derivation;
    }

    /**
     * Sets the value of the derivation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDerivation(String value) {
        this.derivation = value;
    }

    /**
     * Gets the value of the authorOfTribeGenus property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the authorOfTribeGenus property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAuthorOfTribeGenus().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAuthorOfTribeGenus() {
        if (authorOfTribeGenus == null) {
            authorOfTribeGenus = new ArrayList<String>();
        }
        return this.authorOfTribeGenus;
    }

    /**
     * Gets the value of the synonymOfGenusName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSynonymOfGenusName() {
        return synonymOfGenusName;
    }

    /**
     * Sets the value of the synonymOfGenusName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSynonymOfGenusName(String value) {
        this.synonymOfGenusName = value;
    }

    /**
     * Gets the value of the synonymOfSpeciesName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSynonymOfSpeciesName() {
        return synonymOfSpeciesName;
    }

    /**
     * Sets the value of the synonymOfSpeciesName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSynonymOfSpeciesName(String value) {
        this.synonymOfSpeciesName = value;
    }

    /**
     * Gets the value of the synonymOfSubspeciesName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSynonymOfSubspeciesName() {
        return synonymOfSubspeciesName;
    }

    /**
     * Sets the value of the synonymOfSubspeciesName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSynonymOfSubspeciesName(String value) {
        this.synonymOfSubspeciesName = value;
    }

    /**
     * Gets the value of the synonymOfTribeGenus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSynonymOfTribeGenus() {
        return synonymOfTribeGenus;
    }

    /**
     * Sets the value of the synonymOfTribeGenus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSynonymOfTribeGenus(String value) {
        this.synonymOfTribeGenus = value;
    }

    /**
     * Gets the value of the synonymOfTribeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSynonymOfTribeName() {
        return synonymOfTribeName;
    }

    /**
     * Sets the value of the synonymOfTribeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSynonymOfTribeName(String value) {
        this.synonymOfTribeName = value;
    }

    /**
     * Gets the value of the synonymOfVarietyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSynonymOfVarietyName() {
        return synonymOfVarietyName;
    }

    /**
     * Sets the value of the synonymOfVarietyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSynonymOfVarietyName(String value) {
        this.synonymOfVarietyName = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link Description }
     *     
     */
    public Description getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link Description }
     *     
     */
    public void setDescription(Description value) {
        this.description = value;
    }

    /**
     * Gets the value of the numberOfInfrataxa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOfInfrataxa() {
        return numberOfInfrataxa;
    }

    /**
     * Sets the value of the numberOfInfrataxa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOfInfrataxa(String value) {
        this.numberOfInfrataxa = value;
    }

    /**
     * Gets the value of the floweringTime property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the floweringTime property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFloweringTime().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getFloweringTime() {
        if (floweringTime == null) {
            floweringTime = new ArrayList<String>();
        }
        return this.floweringTime;
    }

    /**
     * Gets the value of the habitat property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the habitat property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHabitat().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getHabitat() {
        if (habitat == null) {
            habitat = new ArrayList<String>();
        }
        return this.habitat;
    }

    /**
     * Gets the value of the conservation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConservation() {
        return conservation;
    }

    /**
     * Sets the value of the conservation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConservation(String value) {
        this.conservation = value;
    }

    /**
     * Gets the value of the elevation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElevation() {
        return elevation;
    }

    /**
     * Sets the value of the elevation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElevation(String value) {
        this.elevation = value;
    }

    /**
     * Gets the value of the introduced property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntroduced() {
        return introduced;
    }

    /**
     * Sets the value of the introduced property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntroduced(String value) {
        this.introduced = value;
    }

    /**
     * Gets the value of the caDistributionOrGlobalDistributionOrUsDistribution property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the caDistributionOrGlobalDistributionOrUsDistribution property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCaDistributionOrGlobalDistributionOrUsDistribution().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<String>> getCaDistributionOrGlobalDistributionOrUsDistribution() {
        if (caDistributionOrGlobalDistributionOrUsDistribution == null) {
            caDistributionOrGlobalDistributionOrUsDistribution = new ArrayList<JAXBElement<String>>();
        }
        return this.caDistributionOrGlobalDistributionOrUsDistribution;
    }

    /**
     * Gets the value of the generalDistribution property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the generalDistribution property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGeneralDistribution().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getGeneralDistribution() {
        if (generalDistribution == null) {
            generalDistribution = new ArrayList<String>();
        }
        return this.generalDistribution;
    }

    /**
     * Gets the value of the coupletOrDiscussionOrKey property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the coupletOrDiscussionOrKey property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCoupletOrDiscussionOrKey().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<String>> getCoupletOrDiscussionOrKey() {
        if (coupletOrDiscussionOrKey == null) {
            coupletOrDiscussionOrKey = new ArrayList<JAXBElement<String>>();
        }
        return this.coupletOrDiscussionOrKey;
    }

}
