//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.11 at 12:08:08 PM EDT 
//


package annotationSchema.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="char_type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="modifier" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="color_modifier" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="degree_modifier" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="frequency_modifier" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="from" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="from_inclusive" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="quality_modifier" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="to" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="to_inclusive" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="from_unit" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="to_unit" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="unit" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="upper_restricted" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="negation" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="constraint" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="constraintid" type="{http://www.w3.org/2001/XMLSchema}IDREFS" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "character")
public class Character {

	@XmlAttribute(name = "char_type")
    protected String charType;
    @XmlAttribute
    protected String modifier;
    @XmlAttribute(name = "color_modifier")
    protected String colorModifier;
    @XmlAttribute(name = "degree_modifier")
    protected String degreeModifier;
    @XmlAttribute(name = "frequency_modifier")
    protected String frequencyModifier;
    @XmlAttribute
    protected String from;
    @XmlAttribute(name = "from_inclusive")
    protected Boolean fromInclusive;
    @XmlAttribute(required = true)
    protected String name;
    @XmlAttribute(name = "quality_modifier")
    protected String qualityModifier;
    @XmlAttribute
    protected String to;
    @XmlAttribute(name = "to_inclusive")
    protected Boolean toInclusive;
    @XmlAttribute(name = "from_unit")
    protected String fromUnit;
    @XmlAttribute(name = "to_unit")
    protected String toUnit;
    @XmlAttribute
    protected String unit;
    @XmlAttribute(name = "upper_restricted")
    protected Boolean upperRestricted;
    @XmlAttribute
    protected String value;
    @XmlAttribute
    protected Boolean negation;
    @XmlAttribute
    protected String constraint;
    @XmlAttribute
    @XmlIDREF
    @XmlSchemaType(name = "IDREFS")
    protected List<Object> constraintid;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the charType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCharType() {
        return charType;
    }

    /**
     * Sets the value of the charType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCharType(String value) {
        this.charType = value;
    }

    /**
     * Gets the value of the modifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * Sets the value of the modifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModifier(String value) {
        this.modifier = value;
    }

    /**
     * Gets the value of the colorModifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColorModifier() {
        return colorModifier;
    }

    /**
     * Sets the value of the colorModifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColorModifier(String value) {
        this.colorModifier = value;
    }

    /**
     * Gets the value of the degreeModifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDegreeModifier() {
        return degreeModifier;
    }

    /**
     * Sets the value of the degreeModifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDegreeModifier(String value) {
        this.degreeModifier = value;
    }

    /**
     * Gets the value of the frequencyModifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrequencyModifier() {
        return frequencyModifier;
    }

    /**
     * Sets the value of the frequencyModifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrequencyModifier(String value) {
        this.frequencyModifier = value;
    }

    /**
     * Gets the value of the from property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrom() {
        return from;
    }

    /**
     * Sets the value of the from property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrom(String value) {
        this.from = value;
    }

    /**
     * Gets the value of the fromInclusive property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFromInclusive() {
        return fromInclusive;
    }

    /**
     * Sets the value of the fromInclusive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFromInclusive(Boolean value) {
        this.fromInclusive = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the qualityModifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQualityModifier() {
        return qualityModifier;
    }

    /**
     * Sets the value of the qualityModifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQualityModifier(String value) {
        this.qualityModifier = value;
    }

    /**
     * Gets the value of the to property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTo() {
        return to;
    }

    /**
     * Sets the value of the to property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTo(String value) {
        this.to = value;
    }

    /**
     * Gets the value of the toInclusive property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isToInclusive() {
        return toInclusive;
    }

    /**
     * Sets the value of the toInclusive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setToInclusive(Boolean value) {
        this.toInclusive = value;
    }

    /**
     * Gets the value of the fromUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromUnit() {
        return fromUnit;
    }

    /**
     * Sets the value of the fromUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromUnit(String value) {
        this.fromUnit = value;
    }

    /**
     * Gets the value of the toUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToUnit() {
        return toUnit;
    }

    /**
     * Sets the value of the toUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToUnit(String value) {
        this.toUnit = value;
    }

    /**
     * Gets the value of the unit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnit() {
        return unit;
    }

    /**
     * Sets the value of the unit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnit(String value) {
        this.unit = value;
    }

    /**
     * Gets the value of the upperRestricted property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUpperRestricted() {
        return upperRestricted;
    }

    /**
     * Sets the value of the upperRestricted property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUpperRestricted(Boolean value) {
        this.upperRestricted = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the negation property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNegation() {
        return negation;
    }

    /**
     * Sets the value of the negation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNegation(Boolean value) {
        this.negation = value;
    }

    /**
     * Gets the value of the constraint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConstraint() {
        return constraint;
    }

    /**
     * Sets the value of the constraint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConstraint(String value) {
        this.constraint = value;
    }

    /**
     * Gets the value of the constraintid property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the constraintid property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConstraintid().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getConstraintid() {
        if (constraintid == null) {
            constraintid = new ArrayList<Object>();
        }
        return this.constraintid;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }
    
    /* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Character [");
		if (charType != null)
			builder.append("charType=").append(charType).append(", ");
		if (modifier != null)
			builder.append("modifier=").append(modifier).append(", ");
		if (colorModifier != null)
			builder.append("colorModifier=").append(colorModifier).append(", ");
		if (degreeModifier != null)
			builder.append("degreeModifier=").append(degreeModifier)
					.append(", ");
		if (frequencyModifier != null)
			builder.append("frequencyModifier=").append(frequencyModifier)
					.append(", ");
		if (from != null)
			builder.append("from=").append(from).append(", ");
		if (fromInclusive != null)
			builder.append("fromInclusive=").append(fromInclusive).append(", ");
		if (name != null)
			builder.append("name=").append(name).append(", ");
		if (qualityModifier != null)
			builder.append("qualityModifier=").append(qualityModifier)
					.append(", ");
		if (to != null)
			builder.append("to=").append(to).append(", ");
		if (toInclusive != null)
			builder.append("toInclusive=").append(toInclusive).append(", ");
		if (fromUnit != null)
			builder.append("fromUnit=").append(fromUnit).append(", ");
		if (toUnit != null)
			builder.append("toUnit=").append(toUnit).append(", ");
		if (unit != null)
			builder.append("unit=").append(unit).append(", ");
		if (upperRestricted != null)
			builder.append("upperRestricted=").append(upperRestricted)
					.append(", ");
		if (value != null)
			builder.append("value=").append(value).append(", ");
		if (negation != null)
			builder.append("negation=").append(negation).append(", ");
		if (constraint != null)
			builder.append("constraint=").append(constraint).append(", ");
		if (constraintid != null)
			builder.append("constraintid=").append(constraintid).append(", ");
		if (id != null)
			builder.append("id=").append(id);
		builder.append("]");
		return builder.toString();
	}

}
