//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.09 at 02:33:58 PM MST 
//


package annotationSchema.jaxb;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the annotationSchema.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Discussion_QNAME = new QName("", "discussion");
    private final static QName _GlobalDistribution_QNAME = new QName("", "global_distribution");
    private final static QName _OtherInfo_QNAME = new QName("", "other_info");
    private final static QName _Determination_QNAME = new QName("", "determination");
    private final static QName _CommonName_QNAME = new QName("", "common_name");
    private final static QName _StatementId_QNAME = new QName("", "statement_id");
    private final static QName _Author_QNAME = new QName("", "author");
    private final static QName _NumberOfInfrataxa_QNAME = new QName("", "number_of_infrataxa");
    private final static QName _CaDistribution_QNAME = new QName("", "ca_distribution");
    private final static QName _Conservation_QNAME = new QName("", "conservation");
    private final static QName _SpeciesName_QNAME = new QName("", "species_name");
    private final static QName _GenusName_QNAME = new QName("", "genus_name");
    private final static QName _SubspeciesAuthority_QNAME = new QName("", "subspecies_authority");
    private final static QName _SubspeciesName_QNAME = new QName("", "subspecies_name");
    private final static QName _PlaceInPublication_QNAME = new QName("", "place_in_publication");
    private final static QName _VarietyAuthority_QNAME = new QName("", "variety_authority");
    private final static QName _Text_QNAME = new QName("", "text");
    private final static QName _Etymology_QNAME = new QName("", "etymology");
    private final static QName _VarietyName_QNAME = new QName("", "variety_name");
    private final static QName _Elevation_QNAME = new QName("", "elevation");
    private final static QName _SpeciesAuthority_QNAME = new QName("", "species_authority");
    private final static QName _Number_QNAME = new QName("", "number");
    private final static QName _Phenology_QNAME = new QName("", "phenology");
    private final static QName _Habitat_QNAME = new QName("", "habitat");
    private final static QName _UsDistribution_QNAME = new QName("", "us_distribution");
    private final static QName _NextStatementId_QNAME = new QName("", "next_statement_id");
    private final static QName _Introduced_QNAME = new QName("", "introduced");
    private final static QName _GenusAuthority_QNAME = new QName("", "genus_authority");
    private final static QName _PublicationTitle_QNAME = new QName("", "publication_title");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: annotationSchema.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Character }
     * 
     */
    public Character createCharacter() {
        return new Character();
    }

    /**
     * Create an instance of {@link Relation }
     * 
     */
    public Relation createRelation() {
        return new Relation();
    }

    /**
     * Create an instance of {@link Description }
     * 
     */
    public Description createDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link PlaceOfPublication }
     * 
     */
    public PlaceOfPublication createPlaceOfPublication() {
        return new PlaceOfPublication();
    }

    /**
     * Create an instance of {@link Key }
     * 
     */
    public Key createKey() {
        return new Key();
    }

    /**
     * Create an instance of {@link Treatment }
     * 
     */
    public Treatment createTreatment() {
        return new Treatment();
    }

    /**
     * Create an instance of {@link Structure }
     * 
     */
    public Structure createStructure() {
        return new Structure();
    }

    /**
     * Create an instance of {@link Statement }
     * 
     */
    public Statement createStatement() {
        return new Statement();
    }

    /**
     * Create an instance of {@link KeyStatement }
     * 
     */
    public KeyStatement createKeyStatement() {
        return new KeyStatement();
    }

    /**
     * Create an instance of {@link TaxonIdentification }
     * 
     */
    public TaxonIdentification createTaxonIdentification() {
        return new TaxonIdentification();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "discussion")
    public JAXBElement<String> createDiscussion(String value) {
        return new JAXBElement<String>(_Discussion_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "global_distribution")
    public JAXBElement<String> createGlobalDistribution(String value) {
        return new JAXBElement<String>(_GlobalDistribution_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "other_info")
    public JAXBElement<String> createOtherInfo(String value) {
        return new JAXBElement<String>(_OtherInfo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "determination")
    public JAXBElement<String> createDetermination(String value) {
        return new JAXBElement<String>(_Determination_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "common_name")
    public JAXBElement<String> createCommonName(String value) {
        return new JAXBElement<String>(_CommonName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "statement_id")
    public JAXBElement<BigDecimal> createStatementId(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_StatementId_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "author")
    public JAXBElement<String> createAuthor(String value) {
        return new JAXBElement<String>(_Author_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "number_of_infrataxa")
    public JAXBElement<String> createNumberOfInfrataxa(String value) {
        return new JAXBElement<String>(_NumberOfInfrataxa_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ca_distribution")
    public JAXBElement<String> createCaDistribution(String value) {
        return new JAXBElement<String>(_CaDistribution_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "conservation")
    public JAXBElement<String> createConservation(String value) {
        return new JAXBElement<String>(_Conservation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "species_name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSpeciesName(String value) {
        return new JAXBElement<String>(_SpeciesName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "genus_name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createGenusName(String value) {
        return new JAXBElement<String>(_GenusName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "subspecies_authority")
    public JAXBElement<String> createSubspeciesAuthority(String value) {
        return new JAXBElement<String>(_SubspeciesAuthority_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "subspecies_name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSubspeciesName(String value) {
        return new JAXBElement<String>(_SubspeciesName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "place_in_publication")
    public JAXBElement<String> createPlaceInPublication(String value) {
        return new JAXBElement<String>(_PlaceInPublication_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "variety_authority")
    public JAXBElement<String> createVarietyAuthority(String value) {
        return new JAXBElement<String>(_VarietyAuthority_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "text")
    public JAXBElement<String> createText(String value) {
        return new JAXBElement<String>(_Text_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "etymology")
    public JAXBElement<String> createEtymology(String value) {
        return new JAXBElement<String>(_Etymology_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "variety_name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createVarietyName(String value) {
        return new JAXBElement<String>(_VarietyName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "elevation")
    public JAXBElement<String> createElevation(String value) {
        return new JAXBElement<String>(_Elevation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "species_authority")
    public JAXBElement<String> createSpeciesAuthority(String value) {
        return new JAXBElement<String>(_SpeciesAuthority_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "number")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createNumber(String value) {
        return new JAXBElement<String>(_Number_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "phenology")
    public JAXBElement<String> createPhenology(String value) {
        return new JAXBElement<String>(_Phenology_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "habitat")
    public JAXBElement<String> createHabitat(String value) {
        return new JAXBElement<String>(_Habitat_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "us_distribution")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createUsDistribution(String value) {
        return new JAXBElement<String>(_UsDistribution_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "next_statement_id")
    public JAXBElement<BigDecimal> createNextStatementId(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_NextStatementId_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "introduced")
    public JAXBElement<String> createIntroduced(String value) {
        return new JAXBElement<String>(_Introduced_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "genus_authority")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createGenusAuthority(String value) {
        return new JAXBElement<String>(_GenusAuthority_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "publication_title")
    public JAXBElement<String> createPublicationTitle(String value) {
        return new JAXBElement<String>(_PublicationTitle_QNAME, String.class, null, value);
    }

}
