//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.09 at 02:33:58 PM MST 
//


package annotationSchema.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}number"/>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element ref="{}TaxonIdentification"/>
 *           &lt;element ref="{}author"/>
 *           &lt;element ref="{}common_name"/>
 *           &lt;element ref="{}etymology"/>
 *         &lt;/choice>
 *         &lt;element ref="{}description"/>
 *         &lt;element ref="{}number_of_infrataxa" minOccurs="0"/>
 *         &lt;element ref="{}phenology" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}habitat" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}conservation" minOccurs="0"/>
 *         &lt;element ref="{}elevation" minOccurs="0"/>
 *         &lt;element ref="{}introduced" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element ref="{}ca_distribution"/>
 *           &lt;element ref="{}global_distribution"/>
 *           &lt;element ref="{}us_distribution"/>
 *         &lt;/choice>
 *         &lt;element ref="{}discussion" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}key" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "number",
    "taxonIdentificationOrAuthorOrCommonName",
    "description",
    "numberOfInfrataxa",
    "phenology",
    "habitat",
    "conservation",
    "elevation",
    "introduced",
    "caDistributionOrGlobalDistributionOrUsDistribution",
    "discussion",
    "key"
})
@XmlRootElement(name = "treatment")
public class Treatment {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String number;
    @XmlElementRefs({
        @XmlElementRef(name = "common_name", type = JAXBElement.class),
        @XmlElementRef(name = "author", type = JAXBElement.class),
        @XmlElementRef(name = "etymology", type = JAXBElement.class),
        @XmlElementRef(name = "TaxonIdentification", type = TaxonIdentification.class)
    })
    protected List<Object> taxonIdentificationOrAuthorOrCommonName;
    @XmlElement(required = true)
    protected Description description;
    @XmlElement(name = "number_of_infrataxa")
    protected String numberOfInfrataxa;
    protected List<String> phenology;
    protected List<String> habitat;
    protected String conservation;
    protected String elevation;
    protected String introduced;
    @XmlElementRefs({
        @XmlElementRef(name = "ca_distribution", type = JAXBElement.class),
        @XmlElementRef(name = "global_distribution", type = JAXBElement.class),
        @XmlElementRef(name = "us_distribution", type = JAXBElement.class)
    })
    protected List<JAXBElement<String>> caDistributionOrGlobalDistributionOrUsDistribution;
    protected List<String> discussion;
    protected Key key;

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumber(String value) {
        this.number = value;
    }

    /**
     * Gets the value of the taxonIdentificationOrAuthorOrCommonName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the taxonIdentificationOrAuthorOrCommonName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTaxonIdentificationOrAuthorOrCommonName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link TaxonIdentification }
     * 
     * 
     */
    public List<Object> getTaxonIdentificationOrAuthorOrCommonName() {
        if (taxonIdentificationOrAuthorOrCommonName == null) {
            taxonIdentificationOrAuthorOrCommonName = new ArrayList<Object>();
        }
        return this.taxonIdentificationOrAuthorOrCommonName;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link Description }
     *     
     */
    public Description getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link Description }
     *     
     */
    public void setDescription(Description value) {
        this.description = value;
    }

    /**
     * Gets the value of the numberOfInfrataxa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOfInfrataxa() {
        return numberOfInfrataxa;
    }

    /**
     * Sets the value of the numberOfInfrataxa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOfInfrataxa(String value) {
        this.numberOfInfrataxa = value;
    }

    /**
     * Gets the value of the phenology property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the phenology property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPhenology().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPhenology() {
        if (phenology == null) {
            phenology = new ArrayList<String>();
        }
        return this.phenology;
    }

    /**
     * Gets the value of the habitat property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the habitat property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHabitat().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getHabitat() {
        if (habitat == null) {
            habitat = new ArrayList<String>();
        }
        return this.habitat;
    }

    /**
     * Gets the value of the conservation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConservation() {
        return conservation;
    }

    /**
     * Sets the value of the conservation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConservation(String value) {
        this.conservation = value;
    }

    /**
     * Gets the value of the elevation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElevation() {
        return elevation;
    }

    /**
     * Sets the value of the elevation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElevation(String value) {
        this.elevation = value;
    }

    /**
     * Gets the value of the introduced property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntroduced() {
        return introduced;
    }

    /**
     * Sets the value of the introduced property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntroduced(String value) {
        this.introduced = value;
    }

    /**
     * Gets the value of the caDistributionOrGlobalDistributionOrUsDistribution property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the caDistributionOrGlobalDistributionOrUsDistribution property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCaDistributionOrGlobalDistributionOrUsDistribution().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<String>> getCaDistributionOrGlobalDistributionOrUsDistribution() {
        if (caDistributionOrGlobalDistributionOrUsDistribution == null) {
            caDistributionOrGlobalDistributionOrUsDistribution = new ArrayList<JAXBElement<String>>();
        }
        return this.caDistributionOrGlobalDistributionOrUsDistribution;
    }

    /**
     * Gets the value of the discussion property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the discussion property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDiscussion().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getDiscussion() {
        if (discussion == null) {
            discussion = new ArrayList<String>();
        }
        return this.discussion;
    }

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     {@link Key }
     *     
     */
    public Key getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link Key }
     *     
     */
    public void setKey(Key value) {
        this.key = value;
    }

}
