//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.17 at 07:34:43 PM EDT 
//


package sdd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CharTree_NodeSeq complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CharTree_NodeSeq">
 *   &lt;complexContent>
 *     &lt;extension base="{http://rs.tdwg.org/UBIF/2006/}Seq">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="Node" type="{http://rs.tdwg.org/UBIF/2006/}CharTree_Node" maxOccurs="unbounded"/>
 *         &lt;element name="CharNode" type="{http://rs.tdwg.org/UBIF/2006/}CharTree_Character" maxOccurs="unbounded"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CharTree_NodeSeq", propOrder = {
    "nodeOrCharNode"
})
public class CharTreeNodeSeq
    extends Seq
{

    @XmlElements({
        @XmlElement(name = "CharNode", type = CharTreeCharacter.class),
        @XmlElement(name = "Node", type = CharTreeNode.class)
    })
    protected List<CharTreeAbstractNode> nodeOrCharNode;

    /**
     * Gets the value of the nodeOrCharNode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nodeOrCharNode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNodeOrCharNode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CharTreeCharacter }
     * {@link CharTreeNode }
     * 
     * 
     */
    public List<CharTreeAbstractNode> getNodeOrCharNode() {
        if (nodeOrCharNode == null) {
            nodeOrCharNode = new ArrayList<CharTreeAbstractNode>();
        }
        return this.nodeOrCharNode;
    }

}
