//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.17 at 07:34:43 PM EDT 
//


package sdd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CharacterStateSeq complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CharacterStateSeq">
 *   &lt;complexContent>
 *     &lt;extension base="{http://rs.tdwg.org/UBIF/2006/}Seq">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="StateDefinition" type="{http://rs.tdwg.org/UBIF/2006/}CharacterLocalStateDef"/>
 *         &lt;element name="StateReference" type="{http://rs.tdwg.org/UBIF/2006/}ConceptStateRef"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CharacterStateSeq", propOrder = {
    "stateDefinitionOrStateReference"
})
public class CharacterStateSeq
    extends Seq
{

    @XmlElements({
        @XmlElement(name = "StateReference", type = ConceptStateRef.class),
        @XmlElement(name = "StateDefinition", type = CharacterLocalStateDef.class)
    })
    protected List<Object> stateDefinitionOrStateReference;

    /**
     * Gets the value of the stateDefinitionOrStateReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stateDefinitionOrStateReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStateDefinitionOrStateReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConceptStateRef }
     * {@link CharacterLocalStateDef }
     * 
     * 
     */
    public List<Object> getStateDefinitionOrStateReference() {
        if (stateDefinitionOrStateReference == null) {
            stateDefinitionOrStateReference = new ArrayList<Object>();
        }
        return this.stateDefinitionOrStateReference;
    }

}
