//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.17 at 07:34:43 PM EDT 
//


package sdd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;


/**
 * MediaObject plus core level extensions.
 * 
 * <p>Java class for MediaObjectCore complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MediaObjectCore">
 *   &lt;complexContent>
 *     &lt;extension base="{http://rs.tdwg.org/UBIF/2006/}MediaObject">
 *       &lt;group ref="{http://rs.tdwg.org/UBIF/2006/}MediaObjectCoreExtensions"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MediaObjectCore", propOrder = {
    "type",
    "source",
    "encodedData"
})
public class MediaObjectCore
    extends MediaObject
{

    @XmlElement(name = "Type", required = true)
    protected QName type;
    @XmlElement(name = "Source")
    protected URIRef source;
    @XmlElement(name = "EncodedData")
    protected EncodedContent encodedData;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link QName }
     *     
     */
    public QName getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link QName }
     *     
     */
    public void setType(QName value) {
        this.type = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link URIRef }
     *     
     */
    public URIRef getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link URIRef }
     *     
     */
    public void setSource(URIRef value) {
        this.source = value;
    }

    /**
     * Gets the value of the encodedData property.
     * 
     * @return
     *     possible object is
     *     {@link EncodedContent }
     *     
     */
    public EncodedContent getEncodedData() {
        return encodedData;
    }

    /**
     * Sets the value of the encodedData property.
     * 
     * @param value
     *     allowed object is
     *     {@link EncodedContent }
     *     
     */
    public void setEncodedData(EncodedContent value) {
        this.encodedData = value;
    }

}
