//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.17 at 07:34:43 PM EDT 
//


package sdd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Elements form a sequence, order carries semantics.
 * 
 * <p>Java class for Seq complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Seq">
 *   &lt;complexContent>
 *     &lt;extension base="{http://rs.tdwg.org/UBIF/2006/}CollectionContainer">
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Seq")
@XmlSeeAlso({
    ConceptStateSeq.class,
    CreatorRefSeq.class,
    CharacterStateSeq.class,
    OwnerRefSeq.class,
    ModifierSeq.class,
    TaxonNameRefSeq.class,
    TaxonHierarchyNodeSeq.class,
    CharTreeNodeSeq.class,
    ContributorRefSeq.class,
    RecommendedMeasureSeq.class,
    StoredKeyLeadSeq.class,
    AgentStringSeq.class,
    DescriptiveConceptRefSeq.class
})
public abstract class Seq
    extends CollectionContainer
{


}
