//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.17 at 07:34:43 PM EDT 
//


package sdd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;


/**
 * ValueRange extended with a specification for the kind of value (broad enumerated statistical concepts).
 * 
 * <p>Java class for ValueRangeWithClass complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ValueRangeWithClass">
 *   &lt;complexContent>
 *     &lt;extension base="{http://rs.tdwg.org/UBIF/2006/}ValueRange">
 *       &lt;attribute name="valueclass" type="{http://rs.tdwg.org/UBIF/2006/}UnivarStatMeasureClassEnum" default="CentralMeasure" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ValueRangeWithClass")
public class ValueRangeWithClass
    extends ValueRange
{

    @XmlAttribute
    protected QName valueclass;

    /**
     * Gets the value of the valueclass property.
     * 
     * @return
     *     possible object is
     *     {@link QName }
     *     
     */
    public QName getValueclass() {
        if (valueclass == null) {
            return new QName("http://rs.tdwg.org/UBIF/2006/", "CentralMeasure", "");
        } else {
            return valueclass;
        }
    }

    /**
     * Sets the value of the valueclass property.
     * 
     * @param value
     *     allowed object is
     *     {@link QName }
     *     
     */
    public void setValueclass(QName value) {
        this.valueclass = value;
    }

}
